### PR TITLE
Fix folder duplication.

### LINKED ISSUE #2: Folder conflicts
The project has folders that have the same name, but with different caps.
This causes a problem on windows machines.

### PR DESCRIPTION
**Pull request by Dadadah**
Resolves #2

I loaded the repository on a linux machine and moved everything from the lowercase folders to the uppercase folder. Also fixed the project not importing everything on a fresh import.

### CODE REVIEW

**Comment by Dadadah** [comment]
This will break your references to the DLL's from Colony Survival. We should add these to the project or instruct to put them right outside the repository to work on it.

**Comment by tommykent1210** [comment]
The idea is you don't push .sln, .suo, or .csproj files to the repo, then people can use Visual Studio to create their own project from code. If you push .sln/.suo files, they have specific references to folder structure with direct paths. This will break if we're not all using the same paths.

**Comment by tommykent1210** [comment]
For example, your paths to the DLLs won't work for me, because I keep my development stuff on a different drive to the game itself. And we don't need to bundle the DLL from the game with the code, because people can just add the reference to their actual game directory

**Comment by tommykent1210** [comment]
The alternative is, like you say, we bundle the DLLs from the game in a "Thirdparty" folder, and use relative paths to point to it, that way everyone can use the same build, and the same .sln

**Comment by Dadadah** [comment]
I really think the latter is a better solution. Not updating the project files leads to the project more prone to mistake and making the project less welcoming to new contributers. I will update the PR with this implemented and my master branch updated later today.

**Comment by Dadadah** [comment]
So I created a libs folder and added it to the gitignore. VS will now look for the shared libraries in that folder. I also updated the readme to contain instructions for this.

**Comment by tommykent1210** [comment]
I'd even suggest perhaps removing it from gitignore. That way people can develop on a version that isn't the current release. I'll ask Zun about distributing the core DLL's in our repo

**Comment by Dadadah** [comment]
Sounds great. I'm about to head to sleep, do you think you could merge this before you do more work? It would make developing trade a lot easier.
Cheers.

_Sent from my BLU Life One X2 Mini using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tommykent1210** [comment]
Yeah, I'll merge now, we can make gitignore changes later

**Comment by Dorky106** [comment]
type.cs
as well as the types folder is still lower case, from a fresh first pull.

**Comment by tommykent1210** [comment]
Fixed

**Comment by Dorky106** [comment]
As I can't find any more errors, I'm moving this into the finished section.

**Pull request merged**
